### ISSUE TITLE
Error "It appears tlmgr is not installed." on windows

### ISSUE THREAD

**Issue by maphy-psd** [maphy-psd/texliveonfly#1]
Running the script on windows the following error appears.

Usage: texliveonfly.py [options] file.tex Use option --help for more info. texliveonfly.py: error: texliveonfly.py: It appears tlmgr is not installed. Are you sure you have TeX Live 2010 or later?

X:\Path\To\texlive\2015\bin\win32\runscript.tlu:659: command failed with exit code 2: python.exe x:/Path/To/texlive/2015/texmf-dist/scripts/texliveonfly/texliveonfly.py Y:\Path\to\texfile.tex

**Comment by maphy-psd** [comment]
fixed by 2cee865a3b6f9c83d14178cae5d901dcaac844a1

**Comment by thengineer** [comment]
Hi,
I've just installed texlive on a fresh copy of Windows 10 and it seems that in the version of texliveonfly I installed via `tlmgr` , the patch above is not included. (had to manually apply the patch to get texliveonfly working, which is an awesome thing btw)

**Comment by brdann** [comment]
As of TeXLive 2024 fresh install on Windows via manager isn't applied still :(
