### ISSUE TITLE
texliveonfly doesn't work on Mac OS X El Capitan

### ISSUE THREAD

**Issue by liantze** [maphy-psd/texliveonfly#2]
The prompt to escalate permissions was never displayed, so package installation fails without further information.

A typical message:

```
! LaTeX Error: File `celtic.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.5 \usepackage
               {url}^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on main.log.
```

**Comment by maphy-psd** [comment]
Sry, i don't have a Mac and can't test it. Can you give me some more information please?

**Comment by liantze** [comment]
I think this is related to Apple's new "System Integrity Protection" in El Capitan: http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really

Installing packages using `sudo tlmgr` still works, so this looks like Apple changed something and texliveonfly couldn't even initiate the process to escalate privileges...

If there's anything I can do to produce the necessary logs/messages to help, please let me know!

**Comment by FranklinYu** [comment]
@liantze I have submitted #3, but it seems to take long for @maphy-psd to merge it. If you need it, you can manually patch your own `texliveonfly`.

**Comment by liantze** [comment]
Thanks @franklinyu . At some point, after one of the OS X updates during the past year, `texliveonfly` seemed to work again.
